= Pogramación I: Trabajo Práctico 1
José Herrera <jooherrera4@gmail.com> ; Monarca_Actual <cfk@gmail.com>; Ex_Monarca <nestor@gmail.com>
v1, {docdate}. Docentes Leo y Lucifer (COM-01)
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

== Introducción

El malvado Doctor Gero robó la computadora Commodore 128kb de hackeo del tiempo de
Hackerman, el hacker más poderoso de todos los tiempos.

El Doctor Gero está obsesionado con dominar el mundo, por ese motivo viajó al pasado, a la
segunda guerra mundial, y se refugió en un castillo alemán, su objetivo es reunir a los ejércitos
más malvados de la historia y con ellos poder conquistar el mundo.

Al enterarse de esto, Hackerman, construye una nueva Commodore 128kb de hackeo del
tiempo, y viaja al pasado a la Era Vikinga, para pedirle ayuda a Barbarianna.

La heroína vikinga, Barbarianna, acepta ayudar a Hackerman, y viaja por el tiempo para
enfrentar al Doctor Gero. El malvado Doctor se encuentra refugiado en un antiguo castillo
alemán, repleto de velociraptors que él mismo llevó directamente desde la Era del Hielo.

El objetivo de este trabajo práctico es desarrollar un videojuego en el cual Barbarianna vaya
subiendo por los distintos pisos del antiguo castillo y pueda recuperar el dispositivo de hackeo
del tiempo, sin perder la vida en manos de los peligrosísimos velociraptors.

== Descripción

Se puede manejar a Barbarianna mediante las teclas gamer 'w','a','s','d'. 

Puede subir los pisos del juego solamente si tiene espacio para saltar lo suficiente. Para realizar esta acción se debe apretar 
la tecla 'u'.

Presionando la barra espaciadora lanza un rayo que elimina a los velociraptors. 

Se da por ganado el juego si Barbarianna toca la computadora Commodore 128kb.

Se da por perdido el juego si Barbarianna ya no tiene mas vidas. Si muere y tiene vidas disponibles, vuelve al piso inicial. 


== Implementación

.Clase Juego
[source, java]
----
  //Está constantemente comprobando el estado y comportamiento de los objetos.
  public void tick() {
		time++; 
		if (perdio())
			return;
		if (gano())
			return;
		dibujarFondo();
		dibujarPisos();
		computadora();
		velociraptor();
		barbarianna();
		textoEnPantalla();
	}
  
----

== Conclusiones

Una de las principales dificultades que se han presentado durante el desarrollo de este videojuego fue 
la coordinación para la distribución de tareas. Otra fue el tiempo personal que cada integrante podía dedicarle a este trabajo.

El trabajar solamente con la rama principal hace más dificil trabajar en equipo. 

No tener una metodología de desarrollo o alguien a quien se lo pueda considerar lider de equipo, conlleva a que surjan diferencias o 
malentendidos entre programadores. 

Las reuniones con el docente fueron de mucha ayuda para la refactorización del código fuente.

