= Informe del Trabajo Practico Programacion I (COM 01)

Integrantes
Agustina Mendez, 39707636/2014, <agustina.996@hotmail.com> 
Kevin Montenegro, 39707593/2018, <kevinmontenegroac@gmail.com> 
Gaston Sanchez, 39927254/2019, <gaston.sanchez.gs@gmail.com>  
Martina Soria, 42934129/2020, <marti3014soria@gmail.com>

Docentes
Leonardo Waingarten <lwaingarten@campus.ungs.edu.ar>
Hernan Rondelli <lucifer.unix.cabj@gmail.com>
v1, {docdate}. 

:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

== Introducción

 Este trabajo práctico consistió en desarrollar un mini videojuego con la temática de Castlevania, en la cual el personaje principal y nuestra heroína, Barbarianna, debe detener los malvados planes de dominar el mundo del villano de este mini videojuego, El Doctor Gero, recuperando una computadora de hackeo del tiempo que el mismo Doctor le robo a un poderoso hacker, Hackerman, para poder llevar a cabo sus dichosos planes. 

Para recuperar la computadora y detener al Doctor Gero, Barbarianna debe subir los pisos de un castillo en donde el mismo Doctor se refugia y tratar de sobrevivir a los peligrosos velociraptors que evitan la entrada de cualquier intruso.

Para poder jugar, el usuario debe moverse utilizando la tecla "D" para avanzar; “A" para retroceder y "S" para agacharse.
Para saltar al siguiente piso, el usuario debe utilizar la tecla "U".
Barbarianna puede defenderse de los velociraptors gracias al martillo que el Dios Thor le dio prestado. Para poder utilizarlo, el usuario debe apretar la tecla "BARRA ESPACIADORA".

Si Barbarianna logra llegar al último piso y tocar la computadora, el usuario gana. Por otro lado, si Barbarianna es alcanzada por algún velociraptor, esta vuelve al punto de partida y pierde una de las tres vidas que tiene. Al perder todas las vidas, el usuario pierde el juego.

== Descripción

Se puede manejar a Barbarianna mediante las teclas gamer 'w','a','s','d'. 

Puede subir los pisos del juego solamente si tiene espacio para saltar lo suficiente. Para realizar esta acción se debe apretar 
la tecla 'u'.

Presionando la barra espaciadora lanza un rayo que elimina a los velociraptors. 

Se da por ganado el juego si Barbarianna toca la computadora Commodore 128kb.

Se da por perdido el juego si Barbarianna ya no tiene mas vidas. Si muere y tiene vidas disponibles, vuelve al piso inicial. 


== Implementación


.Esta constantemente comprobando el estado del juego.
[source, java]
----
  public void tick() {
		time++;  //Temporizador para la aparición de un nuevo velociraptor.
		if (perdio())
			return;
		if (gano())
			return;
		dibujarFondo();
		dibujarPisos();
		computadora();
		velociraptor();
		barbarianna();
		textoEnPantalla();
	}
----

.Método de clase de Barbarianna.
[source, java]
----
//Comprueba los estados de Barbarianna. Mediante la interacción del usuario con el teclado, el personaje ejecuta un comportamiento distinto. 
private void barbarianna() {
		if (barbarianna == null) {
			barbarianna = new Barbarianna(entorno.ancho() - 775, entorno.alto() - 102, 2.5);
		}
		if (barbarianna.estaTocandoLaComputadora(computadora)) {
			gano = true;
		}
		if (barbarianna.chocasteConVelociraptor(velociraptors)) {
			barbarianna = null;
			lives--;
			return;
		}
		if (barbarianna.chocasteConRayo(rayoDeVelociraptors)) {
			barbarianna = null;
			lives--;
			return;
		}
		rayoBarbarianna(); // Método de clase que contiene el rayo de Barbarianna.
		if (entorno.estaPresionada('w')) {
			barbarianna.saltar();
		}
		if (entorno.estaPresionada(entorno.TECLA_ESPACIO) && rayoDeBarbarianna == null) {
			rayoDeBarbarianna = barbarianna.dispararRayo();
		}
		if (entorno.estaPresionada('u') && barbarianna.estaHabilitadoParaSubirDePiso(entorno)) {
			barbarianna.cuandoSubirUnPiso(entorno);
		}
		if (entorno.estaPresionada('a')) {
			barbarianna.moverHaciaIzquierda(entorno);
		} else if (entorno.estaPresionada('d')) {
			barbarianna.moverHaciaDerecha(entorno);
		} else if (entorno.estaPresionada('s')) {
			barbarianna.agachar();
		} else {
			barbarianna.estaQuieta();
		}
		if (barbarianna.estaSubiendoUnPiso()) {
			barbarianna.saltarUnPiso(entorno, pisos);
		}
		barbarianna.Actualizar(entorno);
		barbarianna.actualizarPisos(pisos);
		barbarianna.dibujar(entorno);
	}
----

.Método de clase de los velociraptors.
[source, java]
----
private void velociraptor() {
		int idxV = 0; // Iterador 
    //Recorremos todos los velociraptors existentes
		for (Velociraptor v : velociraptors) { 
			if (v != null) {
				if (!v.getEstaVivo()) {
					velociraptors[idxV] = null;
					return;
				} else if (rayoDeBarbarianna != null && velociraptors[idxV].meChocoElRayo(rayoDeBarbarianna)) {
					velociraptors[idxV] = null;
					rayoDeBarbarianna = null;
					points += 10;
					kills++;
				}
				v.dibujar(entorno);
				v.mover(entorno, pisos);
				if (barbarianna != null) {
					if (v.getFueHallada(barbarianna) && rayoDeVelociraptors[idxV] == null) {
						rayoDeVelociraptors[idxV] = v.dispararRayo();
					}
				}
			}
			if (v == null && time > 100) {
				velociraptors[idxV] = new Velociraptor(entorno.ancho() - 100, 90, 2);
				time = 0;
			}
			idxV++;
		}
		rayoVelociraptor(); // Método de clase que contiene el rayo de los velociraptors.
	}
----

== Conclusiones

Una de las principales dificultades que se han presentado durante el desarrollo de este videojuego fue 
la coordinación para la distribución de tareas. Otra fue el tiempo personal que cada integrante podía dedicarle a este trabajo.

El trabajar solamente con la rama principal hace más dificil trabajar en equipo. 

No tener una metodología de desarrollo o alguien a quien se lo pueda considerar lider de equipo, conlleva a que surjan diferencias o 
malentendidos entre programadores. 

Las reuniones con el docente fueron de mucha ayuda para la refactorización del código fuente.

